module.exports = {
  INVALID_MESSAGE_FORMAT: "INVALID_MESSAGE_FORMAT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNAUTHORISED_CONNECTION: "UNAUTHORISED_CONNECTION",
  DUPLICATE_MESSAGE: "DUPLICATE_MESSAGE"
};